// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agent/reload": {
            "post": {
                "description": "重载代理服务路由",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "重载代理服务路由",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/authorizes": {
            "get": {
                "description": "Authorize列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorize"
                ],
                "summary": "Authorize列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorize",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "限制",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "从当前ID开始",
                        "name": "starting_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "从当前ID结束",
                        "name": "ending_before",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "展开数据",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ListAuthorizeResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Authorize",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorize"
                ],
                "summary": "Create Authorize",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorize ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "expand attribute list",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Authorize"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/authorizes/{id}": {
            "get": {
                "description": "Get Authorize",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorize"
                ],
                "summary": "Get Authorize",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorize ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "expand attribute list",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Authorize"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Update Authorize",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorize"
                ],
                "summary": "Update Authorize",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorize ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateAuthorizeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Authorize",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorize"
                ],
                "summary": "Delete Authorize",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AuthorizeID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/certificates": {
            "get": {
                "description": "证书列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "证书"
                ],
                "summary": "证书列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "证书",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "限制",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "从当前ID开始",
                        "name": "starting_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "从当前ID结束",
                        "name": "ending_before",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "展开数据",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ListCertificateResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "创建证书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "证书"
                ],
                "summary": "创建证书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "证书ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "展开数据",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Certificate"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/certificates/{id}": {
            "get": {
                "description": "获取证书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "证书"
                ],
                "summary": "获取证书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "证书ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "展开数据",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Certificate"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "更新证书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "证书"
                ],
                "summary": "更新证书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "证书ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateCertificateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除证书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "证书"
                ],
                "summary": "删除证书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "证书ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/collections": {
            "get": {
                "description": "Collection列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Collection列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "父级ID",
                        "name": "parent_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "获取深度",
                        "name": "depth",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Collection",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pre_page",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "展开数据",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ListCollectionResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Create Collection",
                "parameters": [
                    {
                        "description": "Collection data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateCollectionParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Collection"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/collections/{id}": {
            "get": {
                "description": "Get Collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Get Collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "expand attribute list",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Collection"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Update Collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Update Collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateCollectionParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Collection"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collection"
                ],
                "summary": "Delete Collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CollectionID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/endpoints": {
            "get": {
                "description": "Endpoint list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Endpoint"
                ],
                "summary": "Endpoint list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "get list after id",
                        "name": "starting_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "get list before id",
                        "name": "ending_before",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "expand attribute list",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ListEndpointResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Endpoint"
                ],
                "summary": "Create Endpoint",
                "parameters": [
                    {
                        "description": "Endpoint data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateEndpointParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Endpoint"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/endpoints/{id}": {
            "get": {
                "description": "Get Endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Endpoint"
                ],
                "summary": "Get Endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "expand attribute list",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Endpoint"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Update Endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Endpoint"
                ],
                "summary": "Update Endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateEndpointParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Endpoint"
                ],
                "summary": "Delete Endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "EndpointID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/routes": {
            "get": {
                "description": "路由列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "路由"
                ],
                "summary": "路由列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索路径",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pre_page",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "展开数据",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ListRouteResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "创建路由",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "路由"
                ],
                "summary": "创建路由",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateRouteParam"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.Route"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/routes/{id}": {
            "get": {
                "description": "获取路由",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "路由"
                ],
                "summary": "获取路由",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路由ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "展开数据",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Route"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "更新路由",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "路由"
                ],
                "summary": "更新路由",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路由ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateRouteParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Route"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除路由",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "路由"
                ],
                "summary": "删除路由",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路由ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/server_names": {
            "get": {
                "description": "域名列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名"
                ],
                "summary": "域名列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "域名",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "限制",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "从当前ID开始",
                        "name": "starting_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "从当前ID结束",
                        "name": "ending_before",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "展开数据",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ListServerNameResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "创建域名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名"
                ],
                "summary": "创建域名",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateServerNameParam"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ServerName"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/server_names/{id}": {
            "get": {
                "description": "获取域名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名"
                ],
                "summary": "获取域名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "域名ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "展开数据",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ServerName"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "更新域名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名"
                ],
                "summary": "更新域名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "域名ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "数据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateServerNameParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除域名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名"
                ],
                "summary": "删除域名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "域名ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "User list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "get list after id",
                        "name": "starting_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "get list before id",
                        "name": "ending_before",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "expand attribute list",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ListUserResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateUserParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/users/session": {
            "post": {
                "description": "Create User Session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User Session",
                "parameters": [
                    {
                        "description": "data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateUserSessionParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.CreateSessionResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Get User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "expand attribute list",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Update User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateUserParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpserver.HttpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Authorize": {
            "type": "object",
            "properties": {
                "attribute": {
                    "$ref": "#/definitions/value.AuthorizeAttribute"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.Certificate": {
            "type": "object",
            "properties": {
                "certificate": {
                    "description": "证书",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "dns_names": {
                    "description": "证书支持的域名",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "key": {
                    "description": "私钥",
                    "type": "string"
                },
                "name": {
                    "description": "证书备注名",
                    "type": "string"
                },
                "not_after": {
                    "description": "证书有效期",
                    "type": "string"
                },
                "not_before": {
                    "description": "证书开启时间",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.Collection": {
            "type": "object",
            "properties": {
                "authorize": {
                    "description": "鉴权信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Authorize"
                        }
                    ]
                },
                "authorize_id": {
                    "description": "鉴权信息ID",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endpoint": {
                    "description": "后端服务\n集合中没有设置后端服务的路由默认继承集合的后端服务信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Endpoint"
                        }
                    ]
                },
                "endpoint_id": {
                    "description": "后端服务",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "description": "父级ID",
                    "type": "string"
                },
                "routes": {
                    "description": "路由信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Route"
                    }
                },
                "server_names": {
                    "description": "服务域名\n外部服务访问路由的入口",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ServerName"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.Endpoint": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "endpoint": {
                    "description": "远程服务",
                    "allOf": [
                        {
                            "$ref": "#/definitions/value.ForwardEndpoint"
                        }
                    ]
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "description": "后端名",
                    "type": "string"
                },
                "type": {
                    "description": "服务类型",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.Route": {
            "type": "object",
            "properties": {
                "authorize": {
                    "description": "鉴权信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Authorize"
                        }
                    ]
                },
                "authorize_id": {
                    "description": "鉴权信息ID",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endpoint": {
                    "description": "路由自定义的后端路由",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Endpoint"
                        }
                    ]
                },
                "endpoint_id": {
                    "description": "后端服务",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "match_options": {
                    "description": "路由的特殊匹配规则",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/value.MatchOption"
                    }
                },
                "method": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.ServerName": {
            "type": "object",
            "properties": {
                "certificate": {
                    "description": "证书",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Certificate"
                        }
                    ]
                },
                "certificate_id": {
                    "description": "证书",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "description": "域名",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "httpserver.HttpError": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/httpserver.HttpErrorDetail"
                }
            }
        },
        "httpserver.HttpErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "service.CreateCollectionParam": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "authorize_id": {
                    "description": "鉴权配置",
                    "type": "string"
                },
                "description": {
                    "description": "分组描述",
                    "type": "string"
                },
                "endpoint_id": {
                    "description": "绑定的后端服务",
                    "type": "string"
                },
                "name": {
                    "description": "分组名",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父级节点",
                    "type": "string"
                },
                "server_name_id": {
                    "description": "绑定的域名",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "service.CreateEndpointParam": {
            "type": "object",
            "required": [
                "endpoint",
                "forward_header",
                "name",
                "type"
            ],
            "properties": {
                "endpoint": {
                    "description": "远程服务",
                    "allOf": [
                        {
                            "$ref": "#/definitions/value.ForwardEndpoint"
                        }
                    ]
                },
                "forward_header": {
                    "description": "请求头转发配置",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/value.ForwardHeaderOption"
                    }
                },
                "forward_rewrite": {
                    "description": "重写配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/value.ForwardRewriteOption"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "description": "服务类型",
                    "type": "string"
                }
            }
        },
        "service.CreateRouteParam": {
            "type": "object",
            "required": [
                "collection_id",
                "match_options",
                "method",
                "name",
                "path"
            ],
            "properties": {
                "authorize_id": {
                    "description": "鉴权配置",
                    "type": "string"
                },
                "collection_id": {
                    "description": "路由分组ID",
                    "type": "string"
                },
                "description": {
                    "description": "路由描述",
                    "type": "string"
                },
                "endpoint_id": {
                    "description": "绑定的后端服务",
                    "type": "string"
                },
                "match_options": {
                    "description": "特殊匹配规则",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/value.MatchOption"
                    }
                },
                "method": {
                    "description": "支持方法",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "路由名称",
                    "type": "string"
                },
                "path": {
                    "description": "匹配路径",
                    "type": "string"
                }
            }
        },
        "service.CreateServerNameParam": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "certificate": {
                    "description": "证书信息，直接创建新证书",
                    "allOf": [
                        {
                            "$ref": "#/definitions/value.Certificate"
                        }
                    ]
                },
                "certificate_id": {
                    "description": "证书ID，使用现有的证书",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.CreateSessionResult": {
            "type": "object",
            "properties": {
                "expire_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "service.CreateUserParam": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "service.CreateUserSessionParam": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "service.ListAuthorizeResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Authorize"
                    }
                },
                "has_more": {
                    "type": "boolean"
                }
            }
        },
        "service.ListCertificateResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Certificate"
                    }
                },
                "has_more": {
                    "type": "boolean"
                }
            }
        },
        "service.ListCollectionResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Collection"
                    }
                },
                "has_more": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "service.ListEndpointResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Endpoint"
                    }
                },
                "has_more": {
                    "type": "boolean"
                }
            }
        },
        "service.ListRouteResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Route"
                    }
                },
                "has_more": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "service.ListServerNameResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ServerName"
                    }
                },
                "has_more": {
                    "type": "boolean"
                }
            }
        },
        "service.ListUserResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.User"
                    }
                },
                "has_more": {
                    "type": "boolean"
                }
            }
        },
        "service.UpdateAuthorizeParam": {
            "type": "object",
            "required": [
                "attribute",
                "id",
                "name",
                "type"
            ],
            "properties": {
                "attribute": {
                    "$ref": "#/definitions/value.AuthorizeAttribute"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "service.UpdateCertificateParam": {
            "type": "object",
            "required": [
                "certificate",
                "id",
                "key",
                "name"
            ],
            "properties": {
                "certificate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.UpdateCollectionParam": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "authorize_id": {
                    "description": "鉴权配置",
                    "type": "string"
                },
                "description": {
                    "description": "分组描述",
                    "type": "string"
                },
                "endpoint_id": {
                    "description": "绑定的后端服务",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "description": "分组名",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父级节点",
                    "type": "string"
                },
                "server_name_id": {
                    "description": "绑定的域名",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "service.UpdateEndpointParam": {
            "type": "object",
            "required": [
                "endpoint",
                "forward_header",
                "id",
                "name",
                "type"
            ],
            "properties": {
                "endpoint": {
                    "description": "远程服务",
                    "allOf": [
                        {
                            "$ref": "#/definitions/value.ForwardEndpoint"
                        }
                    ]
                },
                "forward_header": {
                    "description": "请求头转发配置",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/value.ForwardHeaderOption"
                    }
                },
                "forward_rewrite": {
                    "description": "重写配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/value.ForwardRewriteOption"
                        }
                    ]
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "description": "服务类型",
                    "type": "string"
                }
            }
        },
        "service.UpdateRouteParam": {
            "type": "object",
            "required": [
                "collection_id",
                "id",
                "match_options",
                "method",
                "name",
                "path"
            ],
            "properties": {
                "authorize_id": {
                    "description": "鉴权配置",
                    "type": "string"
                },
                "collection_id": {
                    "description": "路由分组ID",
                    "type": "string"
                },
                "description": {
                    "description": "路由描述",
                    "type": "string"
                },
                "endpoint_id": {
                    "description": "绑定的后端服务",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "match_options": {
                    "description": "特殊匹配规则",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/value.MatchOption"
                    }
                },
                "method": {
                    "description": "支持方法",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "路由名称",
                    "type": "string"
                },
                "path": {
                    "description": "匹配路径",
                    "type": "string"
                }
            }
        },
        "service.UpdateServerNameParam": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "certificate": {
                    "description": "证书信息，直接创建新证书",
                    "allOf": [
                        {
                            "$ref": "#/definitions/value.Certificate"
                        }
                    ]
                },
                "certificate_id": {
                    "description": "证书ID，使用现有的证书",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.UpdateUserParam": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "value.AuthorizeAttribute": {
            "type": "object",
            "properties": {
                "binary": {
                    "$ref": "#/definitions/value.AuthorizeAttributeBinary"
                }
            }
        },
        "value.AuthorizeAttributeBinary": {
            "type": "object",
            "required": [
                "sources"
            ],
            "properties": {
                "header": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/value.AuthorizeSource"
                    }
                }
            }
        },
        "value.AuthorizeSource": {
            "type": "object",
            "required": [
                "name",
                "source"
            ],
            "properties": {
                "name": {
                    "description": "匹配值",
                    "type": "string"
                },
                "source": {
                    "description": "匹配源",
                    "type": "string"
                }
            }
        },
        "value.Certificate": {
            "type": "object",
            "required": [
                "certificate",
                "key"
            ],
            "properties": {
                "certificate": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                }
            }
        },
        "value.ForwardEndpoint": {
            "type": "object",
            "properties": {
                "static": {
                    "$ref": "#/definitions/value.ForwardEndpointStatic"
                }
            }
        },
        "value.ForwardEndpointStatic": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/value.ForwardEndpointTarget"
                    }
                },
                "timeout": {
                    "type": "integer"
                }
            }
        },
        "value.ForwardEndpointTarget": {
            "type": "object",
            "required": [
                "address",
                "network"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "value.ForwardHeaderOption": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "value.ForwardRewriteOption": {
            "type": "object",
            "required": [
                "regex",
                "replace"
            ],
            "properties": {
                "regex": {
                    "description": "转发正则",
                    "type": "string"
                },
                "replace": {
                    "description": "转发配置",
                    "type": "string"
                }
            }
        },
        "value.MatchOption": {
            "type": "object",
            "required": [
                "name",
                "source",
                "type",
                "value"
            ],
            "properties": {
                "name": {
                    "description": "匹配值",
                    "type": "string"
                },
                "source": {
                    "description": "匹配源",
                    "type": "string"
                },
                "type": {
                    "description": "匹配方式",
                    "type": "string"
                },
                "value": {
                    "description": "匹配内容",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
