definitions:
  httputil.HttpError:
    properties:
      error:
        type: string
      error_details:
        items:
          type: string
        type: array
    type: object
  monitor.DynamicStatCollection:
    properties:
      cpu_percent:
        items:
          type: number
        type: array
      disk_read:
        items:
          type: integer
        type: array
      disk_read_speed:
        items:
          type: number
        type: array
      disk_usage:
        items:
          type: number
        type: array
      disk_write:
        items:
          type: integer
        type: array
      disk_write_speed:
        items:
          type: number
        type: array
      load_1:
        items:
          type: number
        type: array
      load_5:
        items:
          type: number
        type: array
      load_15:
        items:
          type: number
        type: array
      mem_swap_used:
        items:
          type: number
        type: array
      mem_virtual_used:
        items:
          type: number
        type: array
      net_recv:
        items:
          type: integer
        type: array
      net_recv_speed:
        items:
          type: number
        type: array
      net_send:
        items:
          type: integer
        type: array
      net_send_speed:
        items:
          type: number
        type: array
      time:
        items:
          type: integer
        type: array
    type: object
  monitor.DynamicStatResult:
    properties:
      collection:
        $ref: '#/definitions/monitor.DynamicStatCollection'
      disk_total:
        type: integer
      mem_swap_total:
        type: integer
      mem_virtual_total:
        type: integer
    type: object
  user.CreateSessionResponse:
    properties:
      expire_at:
        type: string
      name:
        type: string
      scopes:
        items:
          type: string
        type: array
      token:
        type: string
      type:
        type: string
      user_id:
        type: string
    type: object
  user.CreateUserRequest:
    properties:
      name:
        type: string
      password:
        type: string
      scopes:
        items:
          type: string
        type: array
    type: object
  user.CreateUserSessionRequest:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  user.ListUserResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/user.UserDto'
        type: array
      total:
        type: integer
    type: object
  user.UpdateUserRequest:
    properties:
      id:
        type: string
      name:
        type: string
      password:
        type: string
      scopes:
        items:
          type: string
        type: array
    required:
    - id
    type: object
  user.UserDto:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        description: 用户名
        type: string
      scopes:
        description: 用户权限
        items:
          type: string
        type: array
      status:
        allOf:
        - $ref: '#/definitions/user.UserStatus'
        description: 用户状态
      updated_at:
        type: string
    type: object
  user.UserStatus:
    enum:
    - active
    - inactive
    type: string
    x-enum-varnames:
    - UserStatusActive
    - UserStatusInactive
info:
  contact: {}
paths:
  /monitor/dynamic-stat:
    get:
      consumes:
      - application/json
      description: List Dynamic Stat
      parameters:
      - description: 开始时间。默认-1h
        in: query
        name: start_time
        type: string
      - description: 结束时间，默认当前时间
        in: query
        name: end_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/monitor.DynamicStatResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
      summary: List Dynamic Stat
      tags:
      - Monitor
  /users:
    get:
      consumes:
      - application/json
      description: User list
      parameters:
      - description: User
        in: query
        name: name
        type: string
      - description: 是否包含total
        in: query
        name: include_total
        type: boolean
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: pre_page
        type: integer
      - collectionFormat: csv
        description: 展开数据
        in: query
        items:
          type: string
        name: expand
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ListUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
      summary: User list
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: User data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
      summary: Create User
      tags:
      - User
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User
      parameters:
      - description: UserID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
      summary: Delete User
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Get User
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - collectionFormat: csv
        description: expand attribute list
        in: query
        items:
          type: string
        name: expand
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
      summary: Get User
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Update User
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
      summary: Update User
      tags:
      - User
  /users/session:
    delete:
      consumes:
      - application/json
      description: Delete User Session
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
      summary: Delete User Session
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create User CreateSession
      parameters:
      - description: data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserSessionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.CreateSessionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
      summary: Create User CreateSession
      tags:
      - User
swagger: "2.0"
